package com.artemisa.domain;
// Generated 27-sep-2015 9:29:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompraRubro generated by hbm2java
 */
@Entity
@Table(name="compra_rubro")
public class CompraRubro extends BaseEntity  implements java.io.Serializable
{
    
    private static final long serialVersionUID = -9219536959709019489L;
    
    private Compra compra;
    private Rubro rubro;
    private double valor;
    
    public CompraRubro() {
    }
    
    public CompraRubro(Compra compra, Rubro rubro, double valor) {
        this.compra = compra;
        this.rubro = rubro;
        this.valor = valor;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_compra", nullable=false)
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_rubro", nullable=false)
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }
    
    
    @Column(name="valor", nullable=false, precision=22, scale=0)
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
}


