package com.artemisa.domain;
// Generated 03-ago-2015 17:24:10 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name="parametro")
public class Parametro  extends BaseEntity implements java.io.Serializable {
    
    private static final long serialVersionUID = 4897382400157348678L;

     private String nombre;
     private String valor;     

    public Parametro() {
    }

	
    public Parametro(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name="valor", nullable=false, length=500)
    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }    
}


