package com.artemisa.domain;
// Generated 27-sep-2015 9:29:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Presentacion generated by hbm2java
 */
@Entity
@Table(name="presentacion"
)
public class Presentacion extends BaseEntity implements java.io.Serializable {
    private static final long serialVersionUID = 46008015017327048L;
    
    private String descripcion;
    private Set<Producto> productos = new HashSet<Producto>(0);
    
    public Presentacion() {
    }
    
    
    public Presentacion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Presentacion(String descripcion, Set<Producto> productos) {
        this.descripcion = descripcion;
        this.productos = productos;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="presentacion")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
}


