package com.artemisa.domain;
// Generated 27-sep-2015 9:29:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
)
public class Producto extends BaseEntity  implements java.io.Serializable {
    private static final long serialVersionUID = 4646447393153038271L;
    
    private String codigo;
    private Set<CompraDetalle> compraDetalles = new HashSet<CompraDetalle>(0);
    private String descripcion;
    private String foto;
    private int unidades;
    private Marca marca;
    private Presentacion presentacion;
    private TipoProducto tipoProducto;
    private Set<Venta> ventas = new HashSet<Venta>(0);
    
    public Producto() {
    }
    
    
    public Producto(String codigo, String foto, Marca marca, Presentacion presentacion, TipoProducto tipoProducto) {
        this.codigo = codigo;
        this.foto = foto;
        this.marca = marca;
        this.presentacion = presentacion;
        this.tipoProducto = tipoProducto;
    }
    public Producto(String codigo, Set<CompraDetalle> compraDetalles, String descripcion, String foto, Marca marca, Presentacion presentacion, TipoProducto tipoProducto, Set<Venta> ventas) {
        this.codigo = codigo;
        this.compraDetalles = compraDetalles;
        this.descripcion = descripcion;
        this.foto = foto;
        this.marca = marca;
        this.presentacion = presentacion;
        this.tipoProducto = tipoProducto;
        this.ventas = ventas;
    }
    
    
    @Column(name="codigo", nullable=false, length=100)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<CompraDetalle> getCompraDetalles() {
        return this.compraDetalles;
    }
    
    public void setCompraDetalles(Set<CompraDetalle> compraDetalles) {
        this.compraDetalles = compraDetalles;
    }
    
    
    @Column(name="descripcion", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    
    @Column(name="foto", nullable=false, length=300)
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="marca", nullable=false)
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="presentacion", nullable=false)
    public Presentacion getPresentacion() {
        return this.presentacion;
    }
    
    public void setPresentacion(Presentacion presentacion) {
        this.presentacion = presentacion;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="tipo_producto", nullable=false)
    public TipoProducto getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(TipoProducto tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }

    @Column(name="unidades", nullable=false)
    public int getUnidades() {
        return unidades;
    }
    
    public void setUnidades(int unidades) {
        this.unidades = unidades;
    }
}


