package com.artemisa.domain;
// Generated 27-sep-2015 9:29:00 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductoPrecio generated by hbm2java
 */
@Entity
@Table(name="producto_precio"
)
public class ProductoPrecio extends BaseEntity  implements java.io.Serializable {
    private static final long serialVersionUID = -480484981624876041L;
    
    private CompraDetalle compraDetalle;
    private Date fecha;
    private double precio;
    
    public ProductoPrecio() {
    }
    
    public ProductoPrecio(CompraDetalle compraDetalle, Date fecha, double precio) {
        this.compraDetalle = compraDetalle;
        this.fecha = fecha;
        this.precio = precio;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_compra_detalle", nullable=false)
    public CompraDetalle getCompraDetalle() {
        return this.compraDetalle;
    }
    
    public void setCompraDetalle(CompraDetalle compraDetalle) {
        this.compraDetalle = compraDetalle;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    
    @Column(name="precio", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
}


