package com.artemisa.domain;
// Generated 27-sep-2015 9:29:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor")
public class Proveedor  extends BaseEntity  implements java.io.Serializable {
    private static final long serialVersionUID = 9043396253830179524L;
    
    private Set<Compra> compras = new HashSet<Compra>(0);
    private String direccion;
    private String nombre;
    private String telefono;
    
    public Proveedor() {
    }
    
    
    public Proveedor(String nombre) {
        this.nombre = nombre;
    }
    public Proveedor(Set<Compra> compras, String direccion, String nombre, String telefono) {
        this.compras = compras;
        this.direccion = direccion;
        this.nombre = nombre;
        this.telefono = telefono;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }
    
    
    @Column(name="direccion", length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
    @Column(name="telefono", length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    } 
}


