package com.artemisa.domain;
// Generated 27-sep-2015 9:29:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rubro generated by hbm2java
 */
@Entity
@Table(name="rubro")
public class Rubro extends BaseEntity implements java.io.Serializable {
    
    private static final long serialVersionUID = 7401567681696659451L;
    
    public static final char SUMA = '+';
    public static final char RESTA = '-';
    
    private String nombre;
    private char operacion;
    private Set<CompraRubro> compraRubros = new HashSet<CompraRubro>(0);
    
    public Rubro() {
    }
    
    
    public Rubro(String nombre, char operacion) {
        this.nombre = nombre;
        this.operacion = operacion;
    }
    public Rubro(String nombre, char operacion, Set<CompraRubro> compraRubros) {
        this.nombre = nombre;
        this.operacion = operacion;
        this.compraRubros = compraRubros;
    }
    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
    @Column(name="operacion", nullable=false, length=1)
    public char getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(char operacion) {
        this.operacion = operacion;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="rubro")
    public Set<CompraRubro> getCompraRubros() {
        return this.compraRubros;
    }
    
    public void setCompraRubros(Set<CompraRubro> compraRubros) {
        this.compraRubros = compraRubros;
    }
}


