package com.artemisa.domain;
// Generated 27-sep-2015 9:29:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoProducto generated by hbm2java
 */
@Entity
@Table(name="tipo_producto"
)
public class TipoProducto  extends BaseEntity implements java.io.Serializable {
    private static final long serialVersionUID = 8590143125237942560L;
    
    private String nombre;
    private Set<Producto> productos = new HashSet<Producto>(0);
    
    public TipoProducto() {
    }
    
    
    public TipoProducto(String nombre) {
        this.nombre = nombre;
    }
    public TipoProducto(String nombre, Set<Producto> productos) {
        this.nombre = nombre;
        this.productos = productos;
    }
    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="tipoProducto")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
}


