package com.artemisa.domain;
// Generated 27-sep-2015 9:29:00 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="venta"
)
public class Venta  extends BaseEntity implements java.io.Serializable {
    private static final long serialVersionUID = 1992087022228825135L;
    
    private int cantidad;
    private Date fechaVenta;
    private double precio;
    private Producto producto;
    
    public Venta() {
    }
    
    public Venta(int cantidad, Date fechaVenta, double precio, Producto producto) {
        this.cantidad = cantidad;
        this.fechaVenta = fechaVenta;
        this.precio = precio;
        this.producto = producto;
    }
    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_venta", nullable=false, length=10)
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    
    
    @Column(name="precio", nullable=false, precision=22, scale=0)
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="producto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
}


